import { fieldsCode, sample } from "./model.mjs";
export function schemaTable(e) {
  return `  ${e.table}: defineTable({
${fieldsCode(e)}
    companyId: v.id("companies"),
    createdAt: v.number(),
    updatedAt: v.number(),
    revision: v.number(),
  })
    .index("by_company", ["companyId"])
${e.fields
  .filter((f) => f.target)
  .map(
    (f) => `    .index("by_company_${f.name}", ["companyId", "${f.name}"])\n`,
  )
  .join(
    "",
  )}    .searchIndex("search_label", { searchField: "${e.labelField}", filterFields: ["companyId"] }),
`;
}
export function referencesModule(entities) {
  const refs = entities.flatMap((e) =>
    e.fields.filter((f) => f.target).map((f) => ({ e, f })),
  );
  return `// Generated relationship guards. Add features through feature:generate; do not edit this file.
import type { MutationCtx } from "./_generated/server";
import type { Id } from "./_generated/dataModel";
${refs.length ? 'import { appError } from "./utils/appError";\n' : ""}
export async function assertNoProductReferences(ctx: MutationCtx, table: string, id: string, companyId: Id<"companies">) {
${
  refs.length
    ? refs
        .map(
          ({ e, f }) => `  if (table === "${f.target}") {
    const dependent = await ctx.db.query("${e.table}")
      .withIndex("by_company_${f.name}", q => q.eq("companyId", companyId).eq("${f.name}", id as Id<"${f.target}">)).first();
    if (dependent) throw appError("CONFLICT", "Remove linked ${e.table} before deleting this record.");
  }`,
        )
        .join("\n")
    : "  void ctx; void table; void id; void companyId;"
}
}
`;
}
export function backend(e) {
  return `import { v } from "convex/values";
import { adminMutation, adminQuery, requireTenant } from "./tenantFunctions";
import type { MutationCtx } from "./_generated/server";
import type { Doc, Id } from "./_generated/dataModel";
import { appError } from "./utils/appError";
import { assertNoProductReferences } from "./productEntityReferences";

const fields = {
${fieldsCode(e)}
};
const row = v.object({ ...fields, _id: v.id("${e.table}"), _creationTime: v.number(),
  companyId: v.id("companies"), createdAt: v.number(), updatedAt: v.number(), revision: v.number() });
type Values = Pick<Doc<"${e.table}">, ${e.fields.map((f) => `"${f.name}"`).join(" | ")}>;

async function validateValues(ctx: MutationCtx, values: Values, companyId: Id<"companies">) {
${e.fields
  .map((f) => {
    if (f.type === "ref")
      return `  const ${f.name}Record = await ctx.db.get(values.${f.name});
  if (!${f.name}Record || ${f.name}Record.companyId !== companyId) throw appError("INVALID_INPUT", "Choose a related record in this workspace.");`;
    if (f.type === "boolean") return "";
    if (f.type === "number")
      return `  if (!Number.isFinite(values.${f.name})) throw appError("INVALID_INPUT", "${f.name} must be a finite number.");`;
    if (f.type === "date")
      return `  if (!/^\\d{4}-\\d{2}-\\d{2}$/.test(values.${f.name}) || !Number.isFinite(Date.parse(values.${f.name})) || new Date(values.${f.name}).toISOString().slice(0, 10) !== values.${f.name}) throw appError("INVALID_INPUT", "${f.name} must be a valid calendar date.");`;
    return `  if (!values.${f.name}.trim() || values.${f.name}.length > ${f.name === e.labelField ? 200 : 2000}) throw appError("INVALID_INPUT", "${f.name} is required and must be at most ${f.name === e.labelField ? 200 : 2000} characters.");`;
  })
  .filter(Boolean)
  .join("\n")}
${e.fields.some((f) => f.target) ? "" : "  void ctx; void companyId;\n"}  return {
${e.fields.map((f) => `    ${f.name}: values.${f.name}${f.type === "string" ? ".trim()" : ""},`).join("\n")}
  };
}

/** Fixed-size indexed pages; search never downloads the whole table. */
export const list = adminQuery({
  args: { cursor: v.union(v.string(), v.null()), search: v.string() },
  returns: v.object({ page: v.array(row), isDone: v.boolean(), continueCursor: v.string() }),
  handler: async (ctx, args) => {
    const companyId = requireTenant(ctx);
    const search = args.search.trim();
    if (search.length > 200) throw appError("INVALID_INPUT", "Search must be at most 200 characters.");
    const query = search
      ? ctx.db.query("${e.table}").withSearchIndex("search_label", q => q.search("${e.labelField}", search).eq("companyId", companyId))
      : ctx.db.query("${e.table}").withIndex("by_company", q => q.eq("companyId", companyId)).order("desc");
    const result = await query.paginate({ cursor: args.cursor, numItems: 15 });
    return { page: result.page, isDone: result.isDone, continueCursor: result.continueCursor };
  },
});

export const get = adminQuery({
  args: { id: v.id("${e.table}") },
  returns: v.union(row, v.null()),
  handler: async (ctx, args) => {
    const companyId = requireTenant(ctx);
    const record = await ctx.db.get(args.id);
    return record?.companyId === companyId ? record : null;
  },
});

export const create = adminMutation({
  args: fields,
  returns: v.id("${e.table}"),
  handler: async (ctx, args) => {
    const companyId = requireTenant(ctx);
    const values = await validateValues(ctx, args, companyId);
    const now = Date.now();
    return await ctx.db.insert("${e.table}", { ...values, companyId, createdAt: now, updatedAt: now, revision: 1 });
  },
});

export const update = adminMutation({
  args: { id: v.id("${e.table}"), expectedRevision: v.number(), ...fields },
  returns: v.id("${e.table}"),
  handler: async (ctx, args) => {
    const companyId = requireTenant(ctx);
    const record = await ctx.db.get(args.id);
    if (!record || record.companyId !== companyId) throw appError("NOT_FOUND", "Record unavailable.");
    if (record.revision !== args.expectedRevision) throw appError("CONFLICT", "This record changed. Close and reopen the editor before saving.");
    const values = await validateValues(ctx, args, companyId);
    await ctx.db.patch(args.id, { ...values, updatedAt: Date.now(), revision: record.revision + 1 });
    return args.id;
  },
});

export const remove = adminMutation({
  args: { id: v.id("${e.table}"), expectedRevision: v.number() },
  returns: v.null(),
  handler: async (ctx, args) => {
    const companyId = requireTenant(ctx);
    const record = await ctx.db.get(args.id);
    if (!record || record.companyId !== companyId) throw appError("NOT_FOUND", "Record unavailable.");
    if (record.revision !== args.expectedRevision) throw appError("CONFLICT", "This record changed. Review it before deleting.");
    await assertNoProductReferences(ctx, "${e.table}", args.id, companyId);
    await ctx.db.delete(args.id);
    return null;
  },
});
`;
}

export function backendTest(e, entities) {
  // Reference fixtures recursively create only known generated entities (generation order is acyclic).
  const needed = new Set();
  function visit(entity) {
    for (const f of entity.fields.filter((f) => f.target)) {
      const target = entities.find((x) => x.table === f.target);
      visit(target);
      needed.add(target);
    }
  }
  visit(e);
  const refSeed = [...needed]
    .map(
      (
        target,
      ) => `  const ${target.table}Id = await client.mutation(api.${target.table}.create, {
${target.fields.map((f) => `    ${f.name}: ${f.target ? f.target + "Id" : sample(f)},`).join("\n")}
  });`,
    )
    .join("\n");
  return `import { convexTest } from "convex-test";
import { describe, expect, test } from "vitest";
import schema from "./schema";
import type { FunctionReturnType } from "convex/server";
import { api } from "./_generated/api";
const makeTest = () => convexTest(schema, import.meta.glob("./**/*.*s"));
type TestContext = ReturnType<typeof makeTest>;
async function seed(t: TestContext, role: "ADMIN" | "READ_ONLY" | "USER" | "AUDITOR" | "SUPER_ADMIN" = "ADMIN") {
  return await t.run(async ctx => {
    const companyId = await ctx.db.insert("companies", { name: role, createdAt: Date.now() });
    const userId = await ctx.db.insert("users", { email: "user@example.test", role, companyId });
    return { companyId, userId };
  });
}
async function values(client: ReturnType<TestContext["withIdentity"]>) {
${refSeed}
  ${needed.size ? "" : "void client;"}
  return {
${e.fields.map((f) => `    ${f.name}: ${f.target ? f.target + "Id" : sample(f)},`).join("\n")}
  };
}
describe("${e.table} generated feature", () => {
  test("create, detail, edit, stale edit and delete", async () => {
    const t = makeTest(); const a = await seed(t); const client = t.withIdentity({ subject: a.userId });
    const input = await values(client);
    const id = await client.mutation(api.${e.table}.create, input);
    expect((await client.query(api.${e.table}.get, { id }))?.companyId).toBe(a.companyId);
    await client.mutation(api.${e.table}.update, { ...input, id, expectedRevision: 1, ${e.labelField}: "Updated" });
    await expect(client.mutation(api.${e.table}.update, { ...input, id, expectedRevision: 1 })).rejects.toThrow("changed");
    await expect(client.mutation(api.${e.table}.remove, { id, expectedRevision: 1 })).rejects.toThrow("changed");
    await client.mutation(api.${e.table}.remove, { id, expectedRevision: 2 });
    expect(await client.query(api.${e.table}.get, { id })).toBeNull();
  });
  test("another company cannot read, edit or delete records", async () => {
    const t = makeTest(); const a = await seed(t); const b = await seed(t);
    const owner = t.withIdentity({ subject: a.userId }); const intruder = t.withIdentity({ subject: b.userId });
    const input = await values(owner); const id = await owner.mutation(api.${e.table}.create, input);
    expect(await intruder.query(api.${e.table}.get, { id })).toBeNull();
    expect((await intruder.query(api.${e.table}.list, { cursor: null, search: "" })).page).toHaveLength(0);
    expect((await intruder.query(api.${e.table}.list, { cursor: null, search: input.${e.labelField} })).page).toHaveLength(0);
    await expect(intruder.mutation(api.${e.table}.update, { ...input, id, expectedRevision: 1 })).rejects.toThrow();
    await expect(intruder.mutation(api.${e.table}.remove, { id, expectedRevision: 1 })).rejects.toThrow();
  });
  test("read-only can view but cannot write; other roles and anonymous callers cannot read", async () => {
    const t = makeTest(); const a = await seed(t); const reader = await seed(t, "READ_ONLY");
    await t.run(ctx => ctx.db.patch(reader.userId, { companyId: a.companyId }));
    const owner = t.withIdentity({ subject: a.userId }); const input = await values(owner);
    const id = await owner.mutation(api.${e.table}.create, input);
    const read = t.withIdentity({ subject: reader.userId });
    expect(await read.query(api.${e.table}.get, { id })).not.toBeNull();
    await expect(read.mutation(api.${e.table}.create, input)).rejects.toThrow();
    await expect(read.mutation(api.${e.table}.update, { ...input, id, expectedRevision: 1 })).rejects.toThrow();
    await expect(read.mutation(api.${e.table}.remove, { id, expectedRevision: 1 })).rejects.toThrow();
    for (const role of ["USER", "AUDITOR"] as const) {
      const user = await seed(t, role);
      await expect(t.withIdentity({ subject: user.userId }).query(api.${e.table}.list, { cursor: null, search: "" })).rejects.toThrow();
    }
    await expect(t.query(api.${e.table}.list, { cursor: null, search: "" })).rejects.toThrow();
  });
  test("super admins must select a company and remain scoped while impersonating", async () => {
    const t = makeTest(); const a = await seed(t); const admin = await seed(t, "SUPER_ADMIN");
    const owner = t.withIdentity({ subject: a.userId }); const input = await values(owner);
    const id = await owner.mutation(api.${e.table}.create, input);
    const client = t.withIdentity({ subject: admin.userId });
    expect(await client.query(api.${e.table}.get, { id })).toBeNull();
    await t.run(ctx => ctx.db.patch(admin.userId, { impersonatingCompanyId: a.companyId }));
    expect(await client.query(api.${e.table}.get, { id })).not.toBeNull();
    await t.run(ctx => ctx.db.patch(admin.userId, { companyId: undefined, impersonatingCompanyId: undefined }));
    await expect(client.query(api.${e.table}.list, { cursor: null, search: "" })).rejects.toThrow();
  });
  test("pages beyond the first 15 rows and searches the whole tenant index", async () => {
    const t = makeTest(); const a = await seed(t); const client = t.withIdentity({ subject: a.userId });
    const input = await values(client);
    for (let i = 0; i < 31; i++) await client.mutation(api.${e.table}.create, { ...input, ${e.labelField}: i === 0 ? "Needle" : "Other" });
    let cursor: string | null = null; const ids = new Set<string>();
    for (let page = 0; page < 4; page++) {
      const result: FunctionReturnType<typeof api.${e.table}.list> = await client.query(api.${e.table}.list, { cursor, search: "" });
      expect(result.page.length).toBeLessThanOrEqual(15);
      result.page.forEach(row => ids.add(row._id));
      if (result.isDone) break;
      cursor = result.continueCursor;
    }
    expect(ids.size).toBe(31);
    expect((await client.query(api.${e.table}.list, { cursor: null, search: "Needle" })).page).toHaveLength(1);
    await expect(client.mutation(api.${e.table}.create, { ...input, ${e.labelField}: "  " })).rejects.toThrow();
  });
${e.fields
  .filter((f) => f.target)
  .map(
    (
      f,
    ) => `  test("${f.name} rejects foreign links and protects referenced records", async () => {
    const t = makeTest(); const a = await seed(t); const b = await seed(t);
    const owner = t.withIdentity({ subject: a.userId }); const other = t.withIdentity({ subject: b.userId });
    const input = await values(owner); const foreign = await values(other);
    await expect(owner.mutation(api.${e.table}.create, { ...input, ${f.name}: foreign.${f.name} })).rejects.toThrow();
    const id = await owner.mutation(api.${e.table}.create, input);
    await expect(owner.mutation(api.${e.table}.update, { ...input, id, expectedRevision: 1, ${f.name}: foreign.${f.name} })).rejects.toThrow();
    await expect(owner.mutation(api.${f.target}.remove, { id: input.${f.name}, expectedRevision: 1 })).rejects.toThrow("linked");
    await owner.mutation(api.${e.table}.remove, { id, expectedRevision: 1 });
    await owner.mutation(api.${f.target}.remove, { id: input.${f.name}, expectedRevision: 1 });
  });`,
  )
  .join("\n")}
});
`;
}

export function entitySchema(e) {
  const table = schemaTable(e)
    .trim()
    .replace(new RegExp("^" + e.table + ": "), "")
    .replace(/,$/, ";");
  return `import { defineTable } from "convex/server";\nimport { v } from "convex/values";\nexport const ${e.singular}Table = ${table}\n`;
}
export function schemaRegistry(entities) {
  return (
    `// Generated table registry. Individual table contracts live in entities/.\n` +
    entities
      .map(
        (e) =>
          `import { ${e.singular}Table } from "./entities/${e.table}Schema";`,
      )
      .join("\n") +
    "\nexport const productEntityTables = {\n" +
    entities.map((e) => `  ${e.table}: ${e.singular}Table,`).join("\n") +
    "\n};\n"
  );
}
