// Generated by product:init from sonae.product.json. Edit the configuration, then preview/apply again.
export const productIdentity = {
  "name": "Hakken",
  "slug": "hakken",
  "title": "Hakken",
  "description": "Hakken — digital asset P&L and AI visibility",
  "tagline": "発見 — discovery. Work out which digital assets make money and why the rest don't, fix the broken stage, and prove it in leads and sales.",
  "brandColorHex": "#E26D28",
  "logoUrlLight": "",
  "logoUrlDark": ""
};
