export type MovementDebugQaPreset = {
  cases: string[];
  detail: string;
  frameIndex: number | null;
  id: string;
  label: string;
  status: "jump" | "blocked";
};

const QA_PRESETS_BY_RECORDING_ID: Record<string, MovementDebugQaPreset[]> = {
  px71h2bsqg9xv8pxyffv5xgaed89wbx3: [
    {
      cases: ["baseline", "first-scoring-frame"],
      detail: "first scoring frame",
      frameIndex: 0,
      id: "baseline",
      label: "Baseline",
      status: "jump",
    },
    {
      cases: ["strongest-squat"],
      detail: "strongest squat proof",
      frameIndex: 11,
      id: "squat",
      label: "Squat",
      status: "jump",
    },
    {
      cases: ["strongest-head-direction"],
      detail: "strongest head direction proof",
      frameIndex: 127,
      id: "head-direction",
      label: "Head",
      status: "jump",
    },
    {
      cases: ["strongest-root-turn"],
      detail: "narrow standing root-turn proof",
      frameIndex: 425,
      id: "root-turn",
      label: "Root Turn",
      status: "jump",
    },
    {
      cases: ["strongest-root-travel"],
      detail: "no passing root-travel frame in the current proof plan",
      frameIndex: null,
      id: "root-travel-blocked",
      label: "Root Travel",
      status: "blocked",
    },
  ],
  px72q2e5m8pw9gctaj11yh36a989wjt7: [
    {
      cases: ["baseline", "first-scoring-frame", "strongest-squat"],
      detail: "baseline and strongest squat proof",
      frameIndex: 0,
      id: "baseline-squat",
      label: "Baseline",
      status: "jump",
    },
    {
      cases: ["strongest-head-direction"],
      detail: "strongest head direction proof",
      frameIndex: 263,
      id: "head-direction",
      label: "Head",
      status: "jump",
    },
    {
      cases: ["strongest-root-turn"],
      detail: "narrow standing root-turn proof",
      frameIndex: 483,
      id: "root-turn",
      label: "Root Turn",
      status: "jump",
    },
  ],
  px736zs97w9axrn39je7pfahc989q8jv: [
    {
      cases: ["baseline", "first-scoring-frame", "strongest-side-bend", "strongest-squat"],
      detail: "best seated partial baseline/side-bend frame",
      frameIndex: 0,
      id: "baseline-side-bend",
      label: "Baseline",
      status: "jump",
    },
    {
      cases: ["first-source-display-divergence"],
      detail: "source/display lower-body divergence",
      frameIndex: 189,
      id: "source-display",
      label: "Divergence",
      status: "jump",
    },
    {
      cases: ["strongest-right-leg-lift"],
      detail: "strongest right leg-lift proof",
      frameIndex: 225,
      id: "right-leg-lift",
      label: "Right Leg",
      status: "jump",
    },
    {
      cases: ["strongest-left-leg-lift"],
      detail: "strongest left leg-lift proof",
      frameIndex: 402,
      id: "left-leg-lift",
      label: "Left Leg",
      status: "jump",
    },
    {
      cases: ["strongest-seated-forward-fold"],
      detail: "seated-forward-fold is still missing proof",
      frameIndex: null,
      id: "seated-forward-fold-blocked",
      label: "Fold Blocker",
      status: "blocked",
    },
  ],
  px74tzfb514yq5zpm2mpt3fdkx89xr2z: [
    {
      cases: ["baseline", "first-scoring-frame"],
      detail: "first scoring frame",
      frameIndex: 0,
      id: "baseline",
      label: "Baseline",
      status: "jump",
    },
    {
      cases: ["strongest-head-direction"],
      detail: "strongest head direction proof",
      frameIndex: 459,
      id: "head-direction",
      label: "Head",
      status: "jump",
    },
    {
      cases: ["strongest-root-turn"],
      detail: "narrow standing root-turn proof",
      frameIndex: 464,
      id: "root-turn",
      label: "Root Turn",
      status: "jump",
    },
    {
      cases: ["strongest-squat"],
      detail: "strongest squat proof",
      frameIndex: 707,
      id: "squat",
      label: "Squat",
      status: "jump",
    },
  ],
  px75fgt11wbg0jvr17j6fc2dvd89trpm: [
    {
      cases: ["first-scoring-frame"],
      detail: "first scoring frame",
      frameIndex: 13,
      id: "first-score",
      label: "Score Start",
      status: "jump",
    },
    {
      cases: ["strongest-standing-arm-raise", "strongest-standing-reach"],
      detail: "focused broad upper-body reach/arm proof",
      frameIndex: 218,
      id: "upper-reach",
      label: "Upper Reach",
      status: "jump",
    },
    {
      cases: ["strongest-standing-twist"],
      detail: "focused broad upper-body twist proof",
      frameIndex: 2894,
      id: "upper-twist",
      label: "Upper Twist",
      status: "jump",
    },
    {
      cases: ["strongest-side-bend"],
      detail: "strongest side-bend proof",
      frameIndex: 2782,
      id: "side-bend",
      label: "Side Bend",
      status: "jump",
    },
    {
      cases: ["strongest-root-travel"],
      detail: "no passing root-travel frame in the current proof plan",
      frameIndex: null,
      id: "root-travel-blocked",
      label: "Root Travel",
      status: "blocked",
    },
  ],
  px7b0y1rcfbe1e1zanknsgefp986f1qs: [
    {
      cases: ["baseline"],
      detail: "baseline frame",
      frameIndex: 0,
      id: "baseline",
      label: "Baseline",
      status: "jump",
    },
    {
      cases: ["first-scoring-frame"],
      detail: "first scoring frame",
      frameIndex: 87,
      id: "first-score",
      label: "Score Start",
      status: "jump",
    },
    {
      cases: ["strongest-squat"],
      detail: "strongest squat proof",
      frameIndex: 370,
      id: "squat",
      label: "Squat",
      status: "jump",
    },
    {
      cases: ["strongest-root-turn"],
      detail: "narrow standing root-turn proof",
      frameIndex: 1020,
      id: "root-turn",
      label: "Root Turn",
      status: "jump",
    },
    {
      cases: ["strongest-head-direction"],
      detail: "strongest head direction proof",
      frameIndex: 1027,
      id: "head-direction",
      label: "Head",
      status: "jump",
    },
    {
      cases: ["first-source-display-divergence"],
      detail: "source/display lower-body divergence",
      frameIndex: 1465,
      id: "source-display",
      label: "Divergence",
      status: "jump",
    },
    {
      cases: ["strongest-left-leg-lift"],
      detail: "strongest left leg-lift proof",
      frameIndex: 1497,
      id: "left-leg-lift",
      label: "Left Leg",
      status: "jump",
    },
    {
      cases: ["strongest-right-leg-lift"],
      detail: "strongest right leg-lift proof",
      frameIndex: 1631,
      id: "right-leg-lift",
      label: "Right Leg",
      status: "jump",
    },
  ],
  px7ebpmfazdrtbad9bpefxnmp589xwj6: [
    {
      cases: ["baseline", "first-scoring-frame"],
      detail: "first scoring frame",
      frameIndex: 0,
      id: "baseline",
      label: "Baseline",
      status: "jump",
    },
    {
      cases: ["strongest-squat"],
      detail: "strongest squat proof",
      frameIndex: 20,
      id: "squat",
      label: "Squat",
      status: "jump",
    },
    {
      cases: ["strongest-head-direction"],
      detail: "strongest head direction proof",
      frameIndex: 180,
      id: "head-direction",
      label: "Head",
      status: "jump",
    },
    {
      cases: ["strongest-root-turn"],
      detail: "narrow standing root-turn proof",
      frameIndex: 212,
      id: "root-turn",
      label: "Root Turn",
      status: "jump",
    },
  ],
  px7fafa0wypmmc5rfz1nzmdvas88n6m0: [
    {
      cases: ["baseline", "strongest-squat"],
      detail: "baseline and strongest squat proof",
      frameIndex: 0,
      id: "baseline-squat",
      label: "Baseline",
      status: "jump",
    },
    {
      cases: ["first-scoring-frame"],
      detail: "first scoring frame",
      frameIndex: 10,
      id: "first-score",
      label: "Score Start",
      status: "jump",
    },
    {
      cases: ["first-source-display-divergence"],
      detail: "source/display lower-body divergence",
      frameIndex: 800,
      id: "source-display",
      label: "Divergence",
      status: "jump",
    },
    {
      cases: ["strongest-left-leg-lift"],
      detail: "strongest left leg-lift proof",
      frameIndex: 860,
      id: "left-leg-lift",
      label: "Left Leg",
      status: "jump",
    },
    {
      cases: ["strongest-right-leg-lift"],
      detail: "strongest right leg-lift proof",
      frameIndex: 1083,
      id: "right-leg-lift",
      label: "Right Leg",
      status: "jump",
    },
    {
      cases: ["strongest-head-direction"],
      detail: "strongest head direction proof",
      frameIndex: 1101,
      id: "head-direction",
      label: "Head",
      status: "jump",
    },
    {
      cases: ["strongest-side-bend"],
      detail: "strongest side-bend proof",
      frameIndex: 1610,
      id: "side-bend",
      label: "Side Bend",
      status: "jump",
    },
    {
      cases: ["strongest-root-turn"],
      detail: "narrow standing root-turn proof",
      frameIndex: 1719,
      id: "root-turn",
      label: "Root Turn",
      status: "jump",
    },
  ],
  px7fmzw2v4yzex6yx3n9dchj0h89x7e3: [
    {
      cases: ["baseline", "first-scoring-frame"],
      detail: "first scoring frame",
      frameIndex: 0,
      id: "baseline",
      label: "Baseline",
      status: "jump",
    },
    {
      cases: ["strongest-squat"],
      detail: "strongest squat proof",
      frameIndex: 10,
      id: "squat",
      label: "Squat",
      status: "jump",
    },
    {
      cases: ["strongest-side-bend"],
      detail: "strongest side-bend proof",
      frameIndex: 11,
      id: "side-bend",
      label: "Side Bend",
      status: "jump",
    },
    {
      cases: ["strongest-head-direction"],
      detail: "strongest head direction proof",
      frameIndex: 537,
      id: "head-direction",
      label: "Head",
      status: "jump",
    },
  ],
};

export function getMovementDebugQaPresets(recordingId: string, frameCount: number) {
  const maxFrameIndex = Math.max(0, frameCount - 1);

  return (QA_PRESETS_BY_RECORDING_ID[recordingId] ?? []).filter((preset) => (
    preset.frameIndex === null || preset.frameIndex <= maxFrameIndex
  ));
}
