#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { parseEnv } from "node:util";
import { PRODUCT_FILE, readProduct, validateProduct } from "./product-config.mjs";
import { requiredEnvironmentKeys } from "./provider-requirements.mjs";

const GENERATED = "// Generated by product:init from hakken.product.json. Edit the configuration, then preview/apply again.\n";
const CONFIG_IMPORT = 'import { productIdentity } from "@/product.identity";\n';
const BACKEND_IMPORT = 'import { productIdentity } from "../product.identity";\n';

function safeFile(root, relative) {
  if (path.isAbsolute(relative) || relative.split(/[\\/]/).includes("..")) throw new Error("Product targets must stay inside the clone.");
  let current = root;
  for (const part of relative.split("/")) {
    current = path.join(current, part);
    if (fs.existsSync(current) || fs.lstatSync(current, { throwIfNoEntry: false })) {
      if (fs.lstatSync(current).isSymbolicLink()) throw new Error("Refusing a symlink in product target: " + relative);
    }
  }
  return current;
}

function replaceOnce(source, before, after, label) {
  const oldCount = source.split(before).length - 1;
  const newCount = source.split(after).length - 1;
  if (newCount === 1 && oldCount === 0) return source;
  if (oldCount !== 1 || newCount !== 0) throw new Error(label + ": expected template code was changed or duplicated. Review it before initialising.");
  return source.replace(before, () => after);
}

function importIdentity(source, statement, client = false) {
  if (source.split(statement).length === 2) return source;
  if (source.includes("productIdentity")) throw new Error("A productIdentity binding already exists. Review the file before initialising.");
  if (!client) return statement + source;
  return replaceOnce(source, '"use client";\n', '"use client";\n' + statement, "Client module");
}

function replaceLine(source, pattern, replacement, label) {
  const matches = [...source.matchAll(new RegExp(pattern, "gm"))];
  if (matches.length !== 1) throw new Error(label + ": expected exactly one configuration line.");
  return source.replace(new RegExp(pattern, "m"), () => replacement);
}

function dotenvValue(key, value) {
  if (!value) return "";
  // Dotenv does not understand JSON's escaped quotes. Verify the exact bytes
  // using the same parser as setup:validate, including literal backslashes.
  for (const quote of ["'", '"', "`", ""]) {
    const encoded = quote + value + quote;
    if (parseEnv(key + "=" + encoded)[key] === value) return encoded;
  }
  throw new Error(key + ": cannot safely quote this environment value. Use fewer quotation styles in the product configuration.");
}

export function buildProductEnvironment(config) {
  const values = {
    NEXT_PUBLIC_APP_URL: config.deployment.appUrl,
    SITE_URL: config.deployment.appUrl,
    INITIAL_SUPER_ADMIN_EMAIL: config.bootstrap.adminEmail,
    RESEND_FROM_EMAIL: config.email.senderAddress ? (config.email.senderName || config.identity.name) + " <" + config.email.senderAddress + ">" : "",
  };
  const keys = [...new Set(["CONVEX_DEPLOYMENT", "NEXT_PUBLIC_CONVEX_URL", "NEXT_PUBLIC_APP_URL", ...requiredEnvironmentKeys(config)])];
  return [
    "# Generated from hakken.product.json. No credentials are stored here.",
    "# Fill in a NEW deployment's values. Nothing is provisioned by product:init.",
    "# Frontend: CONVEX_DEPLOYMENT, NEXT_PUBLIC_CONVEX_URL, NEXT_PUBLIC_APP_URL, CONVEX_SITE_URL.",
    "# Backend: SITE_URL and provider/auth keys. Set these on the chosen Convex deployment.",
    "# Widget signing secret, when selected, is needed in BOTH environments.",
    "# JWT_PRIVATE_KEY/JWKS are generated per deployment by the Convex Auth setup tooling.",
    "# Optional Stripe billing is configured separately in hakken.billing.json.",
    "# Its backend secrets are STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET; see docs/operator/stripe-billing.md.",
    "# setup:validate --profile=production checks a combined inventory; verify:deployment checks backend names only.",
    ...keys.map(key => key + "=" + dotenvValue(key, values[key])),
    "",
  ].join("\n");
}

/** Pure planning over a clone: no scripts, services or Git state are changed. */
export function planProduct(root, config) {
  validateProduct(config);
  root = fs.realpathSync(root);
  const changes = [];
  const read = relative => fs.readFileSync(safeFile(root, relative), "utf8");
  const add = (relative, after) => {
    const filename = safeFile(root, relative);
    const before = fs.existsSync(filename) ? fs.readFileSync(filename, "utf8") : null;
    if (before !== after) changes.push({ path: relative, before, after });
  };
  // A typo in --root must not turn an unrelated project into a Hakken product.
  readProduct(root);
  if (!read("scripts/strip-verticals.mjs").includes("loadKnownVerticals")) throw new Error("Target is not a Hakken framework clone.");
  const manifest = JSON.parse(read("template.verticals.json"));
  if (!manifest.alwaysKeep?.includes("arcade")) throw new Error("The framework must retain Arcade.");
  const json = value => JSON.stringify(value, null, 2) + "\n";
  add(PRODUCT_FILE, json(config));
  const identityPath = "product.identity.ts";
  if (fs.existsSync(safeFile(root, identityPath)) && !read(identityPath).startsWith(GENERATED)) throw new Error("product.identity.ts already exists and is not owned by the initialiser.");
  // Only public branding is emitted; admin email, repository and provider choices
  // are deliberately excluded from the browser module.
  add(identityPath, GENERATED + "export const productIdentity = " + JSON.stringify(config.identity, null, 2) + ";\n");
  if (fs.existsSync(safeFile(root, "product.env.example")) && !read("product.env.example").startsWith("# Generated from hakken.product.json.")) throw new Error("product.env.example already exists and is not owned by the initialiser.");
  add("product.env.example", buildProductEnvironment(config));

  const pkg = JSON.parse(read("package.json"));
  pkg.name = config.identity.slug;
  add("package.json", json(pkg));
  const lock = JSON.parse(read("package-lock.json"));
  if (!lock.packages?.[""]) throw new Error("Expected a current npm lockfile with a root package entry.");
  lock.name = config.identity.slug;
  lock.packages[""].name = config.identity.slug;
  add("package-lock.json", json(lock));

  let layout = importIdentity(read("src/app/layout.tsx"), CONFIG_IMPORT);
  layout = replaceOnce(layout, 'title: "Hakken - Protocol",', "title: productIdentity.title,", "Page title");
  layout = replaceOnce(layout, 'description: "Hakken Living Dossier",', "description: productIdentity.description,", "Page description");
  add("src/app/layout.tsx", layout);

  const navPath = "src/app/(public)/_components/PublicNav.tsx";
  let nav = importIdentity(read(navPath), CONFIG_IMPORT, true);
  nav = replaceOnce(nav, ">HAKKEN</span>", ">{productIdentity.name.toUpperCase()}</span>", "Public navigation name");
  add(navPath, nav);
  const footerPath = "src/app/(public)/_components/PublicFooter.tsx";
  let footer = importIdentity(read(footerPath), CONFIG_IMPORT);
  footer = replaceOnce(footer, ">HAKKEN</span>", ">{productIdentity.name.toUpperCase()}</span>", "Public footer name");
  footer = replaceOnce(footer, "} Hakken. All rights reserved.", "} {productIdentity.name}. All rights reserved.", "Copyright name");
  footer = replaceOnce(footer, "備え — to be prepared. The production layer behind AI products,\n              already built and running, so your budget goes on the part only\n              you can make.", "{productIdentity.tagline}", "Public footer description");
  add(footerPath, footer);

  const settingsPath = "convex/settingsService.ts";
  let settings = importIdentity(read(settingsPath), BACKEND_IMPORT);
  settings = replaceOnce(settings, 'platformName: "Hakken",', "platformName: productIdentity.name,", "Default platform name");
  settings = replaceOnce(settings, 'brandColorHex: "#E26D28",', "brandColorHex: productIdentity.brandColorHex,", "Default brand colour");
  for (const key of ["logoUrlLight", "logoUrlDark"]) {
    settings = replaceOnce(settings, key + ": undefined as string | undefined,", key + ": (productIdentity." + key + " || undefined) as string | undefined,", "Default " + key);
  }
  add(settingsPath, settings);
  const brandingGuard = "src/no-client-specific-fallbacks.test.ts";
  add(brandingGuard, replaceOnce(read(brandingGuard), '"convex/settingsService.ts": 1,', '"convex/settingsService.ts": 0,', "Branding ratchet"));

  let workflow = read(".github/workflows/deploy.yml");
  for (const [key, value] of [["REGION", config.deployment.region], ["SERVICE", config.deployment.service], ["REPO", config.deployment.artifactRepository]]) {
    workflow = replaceLine(workflow, "  " + key + ": [^\\r\\n]+", "  " + key + ": " + value, "Deployment " + key);
  }
  add(".github/workflows/deploy.yml", workflow);
  const heading = config.identity.name.replace(/[\\`*_{}[\]<>#]/g, "");
  let agents = replaceLine(read("AGENTS.md"), "# .+ Agent Handoff", "# " + heading + " Agent Handoff", "Agent guide title");
  agents = replaceLine(agents, "- The remote is expected to be [^\\r\\n]+", "- The remote is expected to be `" + config.deployment.repositoryUrl + "`; do not change its transport without the owner's instruction.", "Agent guide remote");
  add("AGENTS.md", agents);
  let readme = read("README.md");
  if (!/^# [^\r\n]+\r?\n/.test(readme)) throw new Error("README: expected a product title on the first line.");
  readme = readme.replace(/^# [^\r\n]+/, () => "# " + heading);
  add("README.md", readme);
  return { root, config, changes };
}

/** Apply only a fully validated, still-current plan. Restore earlier writes if
 * a later write fails. Atomic replacements also avoid modifying hard-linked files. */
export function applyProduct(plan) {
  let origin = "";
  try { origin = execFileSync("git", ["remote", "get-url", "origin"], { cwd: plan.root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim(); } catch { /* Fresh export has no remote. */ }
  if (/(?:github\.com[:/])roninsatwork\/Sonae(?:\.git)?\/?$/i.test(origin)) throw new Error("Refusing to initialise the Sonae source repository. Apply to a fresh exported clone with its own remote (or no remote).");
  if (configIsFramework(plan.config)) throw new Error("Set the new product's repositoryUrl before applying; it still points at Hakken.");
  for (const change of plan.changes) {
    const filename = safeFile(plan.root, change.path);
    const current = fs.existsSync(filename) ? fs.readFileSync(filename, "utf8") : null;
    if (current !== change.before) throw new Error("Files changed after preview. Preview again before applying.");
  }
  const written = [];
  const write = (relative, contents) => {
    const filename = safeFile(plan.root, relative);
    const mode = fs.existsSync(filename) ? fs.statSync(filename).mode : 0o644;
    const temporary = filename + ".product-init-" + randomUUID();
    try { fs.writeFileSync(temporary, contents, { flag: "wx", mode }); fs.renameSync(temporary, filename); }
    finally { fs.rmSync(temporary, { force: true }); }
  };
  try {
    for (const change of plan.changes) { write(change.path, change.after); written.push(change); }
  } catch (error) {
    for (const change of written.reverse()) {
      if (change.before === null) fs.rmSync(safeFile(plan.root, change.path));
      else write(change.path, change.before);
    }
    throw error;
  }
}

function configIsFramework(config) {
  return /\/roninsatwork\/Sonae(?:\.git)?\/?$/i.test(config.deployment.repositoryUrl);
}

export function initMain(argv = process.argv.slice(2)) {
  let root = process.cwd();
  let configPath;
  let apply = false;
  let json = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--apply") apply = true;
    else if (arg === "--json") json = true;
    else if (arg === "--root" && argv[i + 1]) root = path.resolve(argv[++i]);
    else if (arg === "--config" && argv[i + 1]) configPath = path.resolve(argv[++i]);
    else throw new Error("Use --config <file> [--root <clone>] [--apply] [--json]. Without --apply, this command only previews.");
  }
  if (!configPath) throw new Error("Supply --config <file> with the new product's configuration. The default action is a preview.");
  const plan = planProduct(root, readProduct(root, configPath));
  if (apply) applyProduct(plan);
  const summary = {
    mode: apply ? "applied" : "preview", root: plan.root,
    identity: plan.config.identity, deployment: plan.config.deployment,
    providers: plan.config.providers, features: plan.config.features,
    files: plan.changes.map(change => change.path),
  };
  console.log(JSON.stringify(summary, null, 2));
  if (!json) console.log(apply ? "Product files updated. No install, seed, remote change, provisioning or deployment was run. Review product.env.example and the product setup guide." : "Preview only: no files changed. Review the configuration and listed files, then repeat with --apply to initialise this clone.");
  return 0;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { process.exitCode = initMain(); }
  catch (error) { console.error(error instanceof Error ? error.message : "Product initialisation failed."); process.exitCode = 1; }
}
