/** Local definitions only: no recipe runs commands or configures a live backend. */
export const recipes = [
  {
    id: "service-desk",
    version: 1,
    title: "Service desk",
    purpose:
      "A staff workspace for tracking customers and their service cases.",
    entities: [
      [
        "service-customer",
        "--label-it",
        "Clienti assistenza",
        "--field",
        "name:string",
        "--field",
        "contactEmail:string",
        "--field-label-it",
        "contactEmail=Email di contatto",
      ],
      [
        "service-case",
        "--label-it",
        "Richieste assistenza",
        "--field",
        "title:string",
        "--field",
        "details:string",
        "--field-label-it",
        "details=Dettagli",
        "--field",
        "customerId:ref:serviceCustomers",
        "--field-label-it",
        "customerId=Cliente",
        "--field",
        "closed:boolean",
        "--field-label-it",
        "closed=Chiusa",
      ],
    ],
    setup: [
      "Complete Product Setup with a separate Convex deployment and the product's identity. Create the company and invite its staff with the existing company/user administration screens.",
      "Give staff ADMIN access to the generated records. READ_ONLY can inspect them; ordinary USER accounts cannot access these staff screens. SUPER_ADMIN must select an active company.",
      "If AI drafting is useful, configure a company agent through /admin/agents, choose models in stored configuration, and add approved company knowledge. Review readiness in the agent's settings before activation.",
    ],
    workflow: [
      "Create a service customer with a name and contact email. The email field is plain text; add email-specific validation if sending becomes a requirement.",
      "Create a service case, select that customer, describe the request and leave Closed unticked. Search is by title; open a case to edit its details or close it.",
      "For assisted drafting, staff can ask their configured agent in /app/assistant using only necessary case context. A human reviews and sends the response separately; generated records are not automatically exposed as agent tools.",
    ],
    launch: [
      "Verify staff can create/edit/close cases, a read-only colleague cannot write, and a user in another company cannot read or link these records.",
      "Verify a customer with linked cases cannot be deleted, search/page navigation works, stale edits show a failure, and English/Italian labels are appropriate for the product.",
      "If an agent is enabled, evaluate grounded replies, requests with no answer, sensitive data handling and usage limits using representative cases before activation.",
    ],
    gaps: [
      "This is a staff starter, not a public customer portal. Customer login/access rules, inbound email, response sending, assignments, service-level deadlines and notifications require product-specific work.",
      "Closed is a simple boolean. Agree a status lifecycle and migration before extending it. No customer/case data is seeded and no workflow or outbound action is installed.",
    ],
  },
  {
    id: "project-tracker",
    version: 1,
    title: "Project tracker",
    purpose: "A tenant workspace for projects and their deliverables.",
    entities: [
      [
        "delivery-project",
        "--label-it",
        "Progetti di consegna",
        "--field",
        "name:string",
        "--field",
        "description:string",
        "--field",
        "targetDate:date",
        "--field-label-it",
        "targetDate=Data obiettivo",
      ],
      [
        "deliverable",
        "--label-it",
        "Consegne",
        "--field",
        "title:string",
        "--field",
        "projectId:ref:deliveryProjects",
        "--field-label-it",
        "projectId=Progetto",
        "--field",
        "done:boolean",
        "--field-label-it",
        "done=Completata",
        "--field",
        "estimate:number",
        "--field-label-it",
        "estimate=Stima",
      ],
    ],
    setup: [
      "Complete Product Setup, create a company and invite its team. Assign ADMIN to editors and READ_ONLY to observers. Ordinary USER accounts do not have access to these staff screens.",
      "Agree what Estimate means (for example hours) before entering data. The generated numeric field accepts finite numbers; add non-negative or business-specific constraints before relying on estimates for reporting.",
    ],
    workflow: [
      "Create a delivery project with a name, description and target date. Dates represent calendar dates without a time zone or time of day.",
      "Create deliverables linked to that project, enter an estimate and mark Done as work completes. Project references are restricted to the active company.",
      "Search projects by name and deliverables by title. Use the record pages to edit; concurrent edits are rejected so one colleague cannot silently replace another's work.",
    ],
    launch: [
      "Exercise create/edit/delete in two companies with editor, read-only and ordinary-user accounts. Include forged links to the other company's project.",
      "Verify a project cannot be deleted while deliverables reference it; exercise more than 15 records, date validation and a stale edit.",
      "Review labels in both locales and agree retention, support ownership and backup/restore procedures before real project data is entered.",
    ],
    gaps: [
      "Assignments, dependencies, effort aggregation, dashboards, reminders and external stakeholder access require product rules. This recipe generates no scheduled work or notifications.",
      "Every generated field is required. Optional fields, richer statuses and product-specific validation require deliberate schema/form changes.",
    ],
  },
  {
    id: "knowledge-assistant",
    version: 1,
    title: "Internal knowledge assistant",
    purpose:
      "A guided setup for the existing company knowledge and assistant surfaces.",
    entities: [],
    setup: [
      "Complete Product Setup with the selected chat provider and credentials in the new backend. setup:validate checks configuration completeness; it does not prove provider connectivity.",
      "Create the company and invite its users. Use the existing company knowledge settings to add approved sources; assign an owner and a review date to each source in your operating process.",
      "Create/configure a company agent at /admin/agents, choose models through stored model defaults, and select the intended knowledge sources and tools. Review its settings/readiness before making it active.",
      "Start with retrieval and answers only. Add connector/tool credentials, external actions, budgets and approvals individually when the product requires them. A recipe never supplies credentials or activates an agent.",
    ],
    workflow: [
      "Ask a company question in /app/assistant and verify the answer against its cited source. Test an ambiguous question and a question the knowledge does not answer.",
      "Revise or remove a source through the existing knowledge surface, allow indexing to complete and verify the next answer reflects the current content.",
      "Collect incorrect or unsupported answers, add them to the agent's evaluation cases, improve the instructions/sources, and rerun those cases before changing the active configuration.",
    ],
    launch: [
      "Prove users see only their company's conversations and permitted sources. Try a second company, an unprivileged user and a removed source.",
      "Evaluate source citations, unsupported questions, conflicting/outdated documents and instructions embedded in a document that try to override the agent's rules.",
      "Set usage limits and retention; verify provider failures, exhausted budgets and unavailable knowledge have understandable outcomes. Complete an actual provider call before claiming readiness.",
      "If any write or external-send tool is later enabled, test its approval and retry behaviour separately before launch.",
    ],
    gaps: [
      "No new tables, pages, agents, credentials or knowledge documents are created. This recipe installs a setup/launch guide because the framework already has the required surfaces.",
      "Document ownership, data retention, evaluation examples and permitted actions are product decisions. Public access, paid subscriptions and billing lifecycle rules are separate work.",
    ],
  },
];
